### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by borismattijssen** [borismattijssen/negotiator#10]
- [ ] Fix #9 
- [ ] Joost: Oppo model verifieren
- [ ] Lizzy: Parameters AC tunen a.d.h.v. simulaties
- [ ] Joost + Roy: Combineren van OppoModel & Bidding
- [ ] Report: Introduction (Lizzy)
- [ ] Report: preference elicitation (Lizzy)
- [ ] Report: BOA introduction (Roy)
- [ ] Report: Bidding part (Roy + Boris)
- [ ] Report: Oppo part (Joost)
- [ ] Report: Accept part (Lizzy)
- [ ] Report: Performance analysis - Test methods (Boris/Joost)
- [ ] Report: Performance analysis - ANAC agents (Boris/Joost)
- [ ] Report: Performance analysis - Different perspectives (Boris/Joost)
- [ ] (Report: Discussion) (TBD)
- [ ] Report: Conclusie (TBD)
